[workspace]
resolver = "2"
members = [
  "crates/gproxy-protocol",
  "crates/gproxy-transform",
  "crates/gproxy-common",
  "crates/gproxy-provider-core",
  "crates/gproxy-provider-impl",
  "crates/gproxy-storage",
  "crates/gproxy-core",
  "crates/gproxy-router",
  "crates/gproxy-admin",
  "apps/gproxy",
]

[workspace.package]
version = "0.2.4"
edition = "2024"
license = "AGPL-3.0-or-later"
authors = ["LeenHawk <leenhawk@leenhawk.com>"]
description = "A high-performance LLM proxy server written in Rust."
homepage = "https://gproxy.leenhawk.com"
repository = "https://github.com/LeenHawk/gproxy"
readme = "README.md"

[workspace.dependencies]
anyhow = "1"
async-trait = "0.1"
bytes = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
time = "0.3"
tokio = "1"

[profile.release]
strip = true
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
