[package]
name = "gproxy-common"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
serde.workspace = true
thiserror = "2"
uuid = { version = "1", features = ["v7", "serde"] }
bytes.workspace = true
