[package]
name = "gproxy-common"
version = "0.2.2"
edition = "2024"

[dependencies]
serde = { version = "1", features = ["derive"] }
thiserror = "2"
uuid = { version = "1", features = ["v7", "serde"] }
bytes = "1"
