[package]
name = "gproxy-transform"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
gproxy-protocol = { path = "../gproxy-protocol" }
serde.workspace = true
serde_json.workspace = true
time.workspace = true
