[package]
name = "gproxy-provider-core"
version = "0.1.0"
edition = "2024"

[dependencies]
arc-swap = "1"
async-trait = "0.1"
bytes = "1"
futures-core = "0.3"
http = "1"
gproxy-protocol = { path = "../gproxy-protocol" }
rand = "0.9"
serde_json = "1"
