[package]
name = "gproxy-admin"
version = "0.2.2"
edition = "2024"

[dependencies]
anyhow = "1"
axum = { version = "0.8", features = ["ws"] }
blake3 = "1"
gproxy-core = { path = "../gproxy-core" }
gproxy-storage = { path = "../gproxy-storage" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
serde_urlencoded = "0.7"
tokio = { version = "1", features = ["rt", "macros"] }
