[package]
name = "gproxy-protocol"
version = "0.2.1"
edition = "2024"

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
time = { version = "0.3", features = ["serde", "parsing", "formatting"] }
bytes = "1"
