[package]
name = "gproxy-core"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
anyhow.workspace = true
arc-swap = "1"
bytes.workspace = true
clap = { version = "4", features = ["derive", "env"] }
gproxy-common = { path = "../gproxy-common" }
gproxy-protocol = { path = "../gproxy-protocol" }
gproxy-provider-core = { path = "../gproxy-provider-core" }
gproxy-provider-impl = { path = "../gproxy-provider-impl" }
gproxy-storage = { path = "../gproxy-storage" }
gproxy-transform = { path = "../gproxy-transform" }
http = "1"
futures-util = "0.3"
rand = "0.9"
serde_json.workspace = true
serde_urlencoded = "0.7"
time.workspace = true
tokio = { workspace = true, features = ["net", "rt", "sync", "time"] }
uuid = { version = "1", features = ["v4"] }
wreq = { version = "6.0.0-rc.27", features = ["stream"] }
wreq-util = "3.0.0-rc.9"
